"""initial migration

Revision ID: 246fdf51223f
Revises:
Create Date: 2025-06-10 16:16:06.289954

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "246fdf51223f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "is_verfied", sa.Boolean(), nullable=False, server_default=sa.text("False")
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "secret_key", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###
