"""Add label array column to notes

Revision ID: 59334e32821a
Revises: 246fdf51223f
Create Date: 2025-06-14 12:57:40.361546

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59334e32821a"
down_revision: Union[str, None] = "246fdf51223f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labels", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "labels", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "secret_key", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("notes", "label")
    # ### end Alembic commands ###
